version: "3.9"
services:
  mongodb:
    image: mongo:jammy
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro
  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    restart: always
  client:
    build:
      context: ./client
    volumes:
      - ./client/src:/app/src
    ports:
      - '8080:8080'
    depends_on:
      - server
